name: E2EMatrix
on:
  workflow_call:
    inputs:
      region:
        type: string
        default: "us-east-2"
      k8s_version:
        type: string
        default: "1.30"
      cleanup:
        type: boolean
        required: true
      git_ref:
        type: string
      workflow_trigger:
        type: string
        required: true
      parallelism:
        type: number
        required: false
        default: 100
      cluster_name:
        type: string
        required: false
      eks_endpoint:
        type: string
        required: false
      redact_cluster_details:
        type: boolean
        required: false
        default: false
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:
    inputs:
      region:
        type: choice
        options:
          - "us-east-1"
          - "us-east-2"
          - "us-west-2"
          - "eu-west-1"
        default: "us-east-2"
      k8s_version:
        type: choice
        options:
          - "1.25"
          - "1.26"
          - "1.27"
          - "1.28"
          - "1.29"
          - "1.30"
        default: "1.30"
      cleanup:
        type: boolean
        required: true
        default: true
      git_ref:
        type: string
        required: true
      parallelism:
        type: number
        required: false
        default: 100
      cluster_name:
        type: string
        required: false
      eks_endpoint:
        type: string
        required: false
      redact_cluster_details:
        type: boolean
        required: false
        default: false
# All jobs will run under the following conditions:
#   1. Upstream Karpenter repo triggered the job by schedule, push, or dispatch
#   2. Upstream Karpenter repo triggered the job by workflow_run, which requires maintainer check to succeed
#   3. Downstream fork triggered the job through dispatch and has set 'ENABLE_E2E' in repo environment variables
jobs:
  redact-cluster-details:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.redact_cluster_details == true
        run: |
          # Using add-mask directly on the GHA input results in the secret being printed to logs
          # https://github.com/actions/runner/issues/643
          CLUSTER_NAME="$(jq -r '.inputs.cluster_name' $GITHUB_EVENT_PATH)"
          EKS_ENDPOINT="$(jq -r '.inputs.eks_endpoint' $GITHUB_EVENT_PATH)"
          details=("$CLUSTER_NAME" "$EKS_ENDPOINT")
          for detail in ${details[@]}; do
            if [[ ! -z $detail ]]; then
              echo "::add-mask::$detail"
            fi
          done
  e2e:
    needs: redact-cluster-details
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
      statuses: write # ./.github/actions/commit-status/start
    strategy:
      fail-fast: false
      # Need to unmarshal input since workflow_dispatch provides all inputs as strings, regardless of real type
      max-parallel: ${{ inputs.cluster_name == '' && fromJson(inputs.parallelism) || 1 }}
      matrix:
        suite:
          - name: IPv6
            region: ${{ inputs.region }}
          - name: AMI
            region: ${{ inputs.region }}
          - name: Scheduling
            region: ${{ inputs.region }}
          - name: Storage
            region: ${{ inputs.region }}
          - name: Integration
            region: ${{ inputs.region }}
          - name: NodeClaim
            region: ${{ inputs.region }}
          - name: Consolidation
            region: ${{ inputs.region }}
          - name: Interruption
            region: ${{ inputs.region }}
          - name: Drift
            region: ${{ inputs.region }}
          - name: Expiration
            region: ${{ inputs.region }}
          - name: Chaos
            region: ${{ inputs.region }}
          - name: Termination
            region: ${{ inputs.region }}
          - name: LocalZone
            # LAX is the only local zone available in the CI account, therefore only use us-west-2
            region: us-west-2
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite.name }}
      git_ref: ${{ inputs.git_ref }}
      region: ${{ matrix.suite.region }}
      k8s_version: ${{ inputs.k8s_version }}
      cleanup: ${{ inputs.cleanup }}
      workflow_trigger: ${{ inputs.workflow_trigger }}
      cluster_name: ${{ inputs.cluster_name }}
      eks_endpoint: ${{ inputs.eks_endpoint }}
      redact_cluster_details: ${{ inputs.redact_cluster_details }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  e2e-upgrade:
    needs: redact-cluster-details
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
      statuses: write # ./.github/actions/commit-status/start
    # Don't run if targeting a specific cluster since parallelism is limited to 1
    if: inputs.cluster_name == ''
    uses: ./.github/workflows/e2e-upgrade.yaml
    with:
      from_git_ref: b3076dca62a81caae2d3c4af4fd378c83a901c48
      to_git_ref: ${{ inputs.git_ref }}
      region: ${{ inputs.region }}
      k8s_version: ${{ inputs.k8s_version }}
      cleanup: ${{ inputs.cleanup }}
      workflow_trigger: ${{ inputs.workflow_trigger }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
